### ISSUE TITLE
[package] boost/1.72.0: boost stacktrace disabled due to wrong compile flags 

### ISSUE THREAD

**Issue by kristofbruyninckx** [conan-io/conan-center-index#10925]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.72.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.47.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=RelWithDebInfo
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Create a conan packages that requires this library. Leave options as default. 

Conan inspect output: 

```
name: boost
version: 1.72.0
url: https://github.com/conan-io/conan-center-index
homepage: https://www.boost.org
license: BSL-1.0
author: None
description: Boost provides free peer-reviewed portable C++ source libraries
topics: ('libraries', 'cpp')
generators: ['txt']
exports: None
exports_sources: None
short_paths: True
apply_env: True
build_policy: None
revision_mode: hash
settings: ('os', 'arch', 'compiler', 'build_type')
options:
    addr2line_location: ANY
    asio_no_deprecated: [True, False]
    buildid: ANY
    bzip2: [True, False]
    debug_level: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    diagnostic_definitions: [True, False]
    error_code_header_only: [True, False]
    extra_b2_flags: ANY
    fPIC: [True, False]
    filesystem_no_deprecated: [True, False]
    header_only: [True, False]
    i18n_backend: ['iconv', 'icu', None, 'deprecated']
    i18n_backend_iconv: ['libc', 'libiconv', 'off']
    i18n_backend_icu: [True, False]
    layout: ['system', 'versioned', 'tagged', 'b2-default']
    lzma: [True, False]
    magic_autolink: [True, False]
    multithreading: [True, False]
    namespace: ANY
    namespace_alias: [True, False]
    numa: [True, False]
    pch: [True, False]
    python_buildid: ANY
    python_executable: ANY
    python_version: ANY
    segmented_stacks: [True, False]
    shared: [True, False]
    system_no_deprecated: [True, False]
    system_use_utf8: [True, False]
    visibility: ['global', 'protected', 'hidden']
    with_stacktrace_backtrace: [True, False]
    without_atomic: [True, False]
    without_chrono: [True, False]
    without_container: [True, False]
    without_context: [True, False]
    without_contract: [True, False]
    without_coroutine: [True, False]
    without_date_time: [True, False]
    without_exception: [True, False]
    without_fiber: [True, False]
    without_filesystem: [True, False]
    without_graph: [True, False]
    without_graph_parallel: [True, False]
    without_iostreams: [True, False]
    without_json: [True, False]
    without_locale: [True, False]
    without_log: [True, False]
    without_math: [True, False]
    without_mpi: [True, False]
    without_nowide: [True, False]
    without_program_options: [True, False]
    without_python: [True, False]
    without_random: [True, False]
    without_regex: [True, False]
    without_serialization: [True, False]
    without_stacktrace: [True, False]
    without_system: [True, False]
    without_test: [True, False]
    without_thread: [True, False]
    without_timer: [True, False]
    without_type_erasure: [True, False]
    without_wave: [True, False]
    zlib: [True, False]
    zstd: [True, False]
default_options:
    addr2line_location: /usr/bin/addr2line
    asio_no_deprecated: False
    buildid: None
    bzip2: True
    debug_level: 0
    diagnostic_definitions: False
    error_code_header_only: False
    extra_b2_flags: None
    fPIC: True
    filesystem_no_deprecated: False
    header_only: False
    i18n_backend: deprecated
    i18n_backend_iconv: libc
    i18n_backend_icu: False
    layout: system
    lzma: False
    magic_autolink: False
    multithreading: True
    namespace: boost
    namespace_alias: False
    numa: True
    pch: True
    python_buildid: None
    python_executable: None
    python_version: None
    segmented_stacks: False
    shared: False
    system_no_deprecated: False
    system_use_utf8: False
    visibility: hidden
    with_stacktrace_backtrace: True
    without_atomic: False
    without_chrono: False
    without_container: False
    without_context: False
    without_contract: False
    without_coroutine: False
    without_date_time: False
    without_exception: False
    without_fiber: False
    without_filesystem: False
    without_graph: False
    without_graph_parallel: True
    without_iostreams: False
    without_json: False
    without_locale: False
    without_log: False
    without_math: False
    without_mpi: True
    without_nowide: False
    without_program_options: False
    without_python: True
    without_random: False
    without_regex: False
    without_serialization: False
    without_stacktrace: False
    without_system: False
    without_test: False
    without_thread: False
    without_timer: False
    without_type_erasure: False
    without_wave: False
    zlib: True
    zstd: False
deprecated: None
```

The option `without_backtrace` is False, while `with_stacktrace_backtrace` is True. 

when doing a `conan install` with the cmake generator, the `conanbuildinfo.cmake` sets the following compile flags

```
set(CONAN_DEFINES_BOOST "-DBOOST_STACKTRACE_ADDR2LINE_LOCATION=\"/usr/bin/addr2line\""
			"-DBOOST_STACKTRACE_USE_ADDR2LINE"
			"-DBOOST_STACKTRACE_USE_BACKTRACE"
			"-DBOOST_STACKTRACE_USE_NOOP")
set(CONAN_BUILD_MODULES_PATHS_BOOST )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_BOOST "BOOST_STACKTRACE_ADDR2LINE_LOCATION=\"/usr/bin/addr2line\""
			"BOOST_STACKTRACE_USE_ADDR2LINE"
			"BOOST_STACKTRACE_USE_BACKTRACE"
			"BOOST_STACKTRACE_USE_NOOP")

```

According to https://www.boost.org/doc/libs/master/doc/html/stacktrace/configuration_and_build.html, it seems to me that we only want one of these options, being BOOST_STACKTRACE_USE_BACKTRACE With the default conan options.
