### ISSUE TITLE
[package] zlib/1.2.11: Mirror mechanism is broken

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1095]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.11**
  * Operating System+version: **Windows 10**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`conan install zlib/1.2.11@ -b`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: zlib/1.2.11: Error in source() method, line 35
        tools.get(**self.conan_data["sources"]["{}_mirror".format(self.version)])
        KeyError: '1.2.11_mirror'
```

</details>

Content of conandata.yml in source and export directories:

```yaml
sources:
  1.2.11:
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: https://zlib.net/zlib-1.2.11.tar.gz
```

1.2.11_mirror field is missing (deleted by conan install through a new feature?).

Workaround: use an array of urls under version field in conandata.yml, and replace try/except by a loop.
