### ISSUE TITLE
[request] libmysqlclient/8.0.30

### ISSUE THREAD

**Issue by byonoy-dne** [conan-io/conan-center-index#12388]
### Package Details
  * Package Name/Version: **libmysqlclient/8.0.30**
  * Changelog: **https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

I don't really care about the new version, but for some reason the sources for 8.0.29 aren't available at mysql.com anymore. Consequently, building libmysqlclient and dependants (Qt in my case) from source fails.

For reference, this is where the sources should be: https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.29.tar.gz
But they're not. Release 8.0.29 also isn't listed in the download archive at https://downloads.mysql.com/archives/community/
Weird...

**Comment by dornbirndevelops** [comment]
@byonoy-dne I can also verify that the download links used by the recipe are broken.
The website seem to have moved them to this page here: https://downloads.mysql.com/archives/community/

The updated links for `8.0.25` and `8.0.17` are there, but `8.0.29` is not yet available yet unfortunately.
I was able to build the previous versions with these two links (checksum also matched).

```yml
8.0.25:
  url: "https://downloads.mysql.com/archives/get/p/23/file/mysql-8.0.25.tar.gz"
  sha256: "c16aa9cf621bc028efba2bb11f3c36a323b125fa0d108ff92fab60e46309206e"
8.0.17:
  url: "https://downloads.mysql.com/archives/get/p/23/file/mysql-8.0.17.tar.gz"
  sha256: "c6e3f38199a77bfd8a4925ca00b252d3b6159b90e4980c7232f1c58d6ca759d6"
```
