### ISSUE TITLE
[package] <troldal-zippy>/<cci.20200622>: sources SHA256 is wrong

### ISSUE THREAD

**Issue by edupaz2** [conan-io/conan-center-index#12491]
### Package and Environment Details

* Package Name/Version: **troldal-zippy/cci.20200622**

From the `conandata.yml` file:
```
sources:
  "cci.20200622":
    url: "https://github.com/troldal/Zippy/archive/a838de8522f9051df0d1b202473bb6befe648702.tar.gz"
    sha256: "8be803861b69c51179ade1f2ce62f07fb1f2d301a084d705c8ec2374db22071a"
```

But the SHA256 of the downloaded file is `0233303a49bae9f705cb25c44e7f8c9917c49a90c8e314ca79f48dd23dd1a836`.

This was working in the past but, at some point, it stopped working.

### Logs

<details><summary>Click to expand log</summary>

```
troldal-zippy/cci.20200622@xxx/zzz: Configuring sources in /Users/UUUU/.conan/data/troldal-zippy/cci.20200622/xxx/zzz/source
Downloading a838de8522f9051df0d1b202473bb6befe648702.tar.gz completed [387.92k]                        
ERROR: troldal-zippy/cci.20200622@xxx/zzz: Error in source() method, line 50
	destination=self._source_subfolder, strip_root=True)
	ConanException: sha256 signature failed for 'a838de8522f9051df0d1b202473bb6befe648702.tar.gz' file. 
 Provided signature: 8be803861b69c51179ade1f2ce62f07fb1f2d301a084d705c8ec2374db22071a  
 Computed signature: 0233303a49bae9f705cb25c44e7f8c9917c49a90c8e314ca79f48dd23dd1a836
```

</details>
