### ISSUE TITLE
[question] requirements versions in yml?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1411]
Currently, dependencies versions are hardcoded in conanfile.py
For most recipes, it plays well whatever the library version.

But I'm trying to package Vulkan-ValidationLayers.
It has 3 dependencies:
- Vulkan-Headers
- glslang
- SPIRV-Tools

Vulkan-Headers is not backward compatible. The version of Vulkan-ValidationLayers is tightly coupled with Vulkan-Headers one.
glslang and SPIRV-Tools seem to be backward compatible (not sure, but I was able to build "old" versions of Vulkan-ValidationLayers with recent versions of glslang and SPIRV-Tools).

Even if Vulkan-ValidationLayers and Vulkan-Headers follow more or less the same versionning, there is not always a perfect match.

Here is an example of what I could use in conandata.yml:

```yml
requirements:
  "1.2.135.0":
    - name: "glslang"
      version: "8.13.3559" # not compatible, missing members in spv namespace
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.2.135.0" # strict requirement
  "1.2.131.2":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.2.131.1" # strict requirement, there is no 1.2.131.2 for vulkan-headers
  "1.2.131.1":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.2.131.1" # strict requirement
  "1.1.130.0":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.1.130.0" # strict requirement
  "1.1.126.0":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.1.126.0" # strict requirement
  "1.1.121.0":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.1.121.0" # strict requirement
  "1.1.114.0":
    - name: "glslang"
      version: "8.13.3559"
    - name: "spirv-tools"
      version: "2020.1"
    - name: "vulkan-headers"
      version: "1.1.114.0" # strict requirement
```

In this example glslang and spirv-tools could be hard coded in conanfile I guess, but not vulkan-headers.

**Comment by uilianries** [comment]
Interesting case, but it's rare for a new feature in conadata.yml. I would prefer keeping conditions in conanfile.py. Also, it would require a new change in Conan hooks to accept that new key.

**Comment by SpaceIm** [comment]
Let say it is harcoded with:
- general case: `self.requires("vulkan-headers/{}".format(self.version))`
- specific cases: `self.requires("vulkan-headers/{}".format(_get_vulkan_headers_version(self.version)))`

It requires a modification of conanfile.py each time a new specific case arises, triggering new package build for all versions :/

**Comment by SpaceIm** [comment]
It appears that there is only one version of Vulkan-ValidationLayers which requires a different version of Vulkan-Headers than its own version.
Thereby it's acceptable to do something like this:

```python
    def requirements(self):
        self.requires.add("glslang/8.13.3559")
        self.requires.add("spirv-tools/2020.1")
        self.requires.add("vulkan-headers/{}".format(self._get_vulkan_headers_version()))

    def _get_vulkan_headers_version(self):
        return {
            "1.2.131.2": "1.2.131.1"
        }.get(str(self.version), str(self.version))
```

**Comment by uilianries** [comment]
@SpaceIm thanks for checking it. Yeah, `_get_vulkan_headers_version` looks good enough if possible.

**Comment by jgsogo** [comment]
Is this something fixed? Is there anything else to consider here?

Thanks!

**Comment by SpaceIm** [comment]
@jsgogo I didn't know what to answer.

Now I think that it's still required in order to document compatible versions and raise in `build()` (`validate()` later) if depencencies compatible versions are not honored. Sort of version range without true version range implementation of conan client.

we could allow this in conandata.yml:

```yml
requirements:
  "1.2.135.0":
    - name: "glslang"
      version: ">=8.13.3559"
```

in conanfile.py:

```python
def build():
    for req in self.conan_data.get("requirements", {}).get(self.version, []):
        if req.name in self.deps_cpp_info and not tools.check_version_against_version_range(req.version, self.deps_cpp_info[req.name].version):
            raise ConanInvalidConfiguration("{} {} requires {} {}".format(self.name, self.version, req.name, req.version))
```
