### ISSUE TITLE
[package] llvm-core/11.1.0: Missing patch file breaks conan install

### ISSUE THREAD

**Issue by nick-schultz** [conan-io/conan-center-index#14636]
### Description

the llvm `source` step is complaining about a missing patch file:

`patches/11.1.0-vs2019.patch`

I see it referenced in the recipe:

**11.1.0/\_/\_/export/conandata.yml**
```
patches:
  11.1.0:
  - base_path: source
    patch_file: patches/11.1.0-vs2019.patch
  - base_path: source
    patch_file: patches/11.1.0-cmake.patch
  - base_path: source
    patch_file: patches/11.1.0-native.patch
sources:
  11.1.0:
    sha256: ce8508e318a01a63d4e8b3090ab2ded3c598a50258cc49e2625b9120d4c03ea5
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz
```

**11.1.0/\_/\_/export/conanfile.py**
```
    def _patch_sources(self):
        for patch in self.conan_data.get('patches', {}).get(self.version, []):
            tools.patch(**patch)
```

it does not look like the patch is in the source package:
```
$ find /....../.conan/data/llvm-core/11.1.0/_/_/export_source/
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/CMakeLists.txt
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/patches
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/patches/11x
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/patches/11x/11.1.0-cmake.patch
/....../.conan/data/llvm-core/11.1.0/_/_/export_source/patches/11x/11.1.0-native.patch
```

### Package and Environment Details

* Package Name/Version: **llvm-core/11.1.0**
* Operating System+version: **RHEL7**
* Compiler+version: **GCC 6**
* Conan version: **conan 1.55.0**
* Python version: **Python 3.9.1**

### Conan profile

```
$ conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce

`conan install llvm-core/11.1.0@ --profile=default --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
$ conan install llvm-core/11.1.0@ --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

WARN: libxml2/2.9.10: requirement zlib/1.2.12 overridden by llvm-core/11.1.0 to zlib/1.2.11 
Installing package: llvm-core/11.1.0
Requirements
    libiconv/1.16 from 'conancenter' - Cache
    libxml2/2.9.10 from 'conancenter' - Cache
    llvm-core/11.1.0 from 'gfxip_conan_local' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    libiconv/1.16:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Cache
    libxml2/2.9.10:54d21a8267df879e6a9583a5f94fd4f66069abb4 - Cache
    llvm-core/11.1.0:171a154f18a0b89d8f5ee019fbb01a901877f33c - Build
    zlib/1.2.11:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Cache

Installing (downloading, building) binaries...
libiconv/1.16: Already installed!
libiconv/1.16: Appending PATH environment var: /....../.conan/data/libiconv/1.16/_/_/package/f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb/bin
zlib/1.2.11: Already installed!
libxml2/2.9.10: Already installed!
libxml2/2.9.10: Appending PATH environment variable: /....../.conan/data/libxml2/2.9.10/_/_/package/54d21a8267df879e6a9583a5f94fd4f66069abb4/bin
llvm-core/11.1.0: WARN: Trying to remove corrupted source folder
llvm-core/11.1.0: WARN: This can take a while for big packages
llvm-core/11.1.0: Configuring sources in /....../.conan/data/llvm-core/11.1.0/_/_/source
Downloading llvm-11.1.0.src.tar.xz completed [38003.20k]                                 

ERROR: llvm-core/11.1.0: Error in source() method, line 202
        self._patch_sources()
while calling '_patch_sources', line 95
        tools.patch(**patch)
        FileNotFoundError: [Errno 2] No such file or directory: 'patches/11.1.0-vs2019.patch'

$ 

```

</details>
