### ISSUE TITLE
[question] Immutable sources (KB-H010) Problem

### ISSUE THREAD

**Issue by cprieto** [conan-io/conan-center-index#16763]
### What is your question?

I am working in a new recipe for Conan center index for an open source unit test framework, Criterion. Locally I can make it build and all of that. The problem is, the repository heavily depends on git submodules.

Ok, I tried using the following logic:

 - Download the provided GitHub release zip file using `get`
 - Download the required dependencies from their repos as well and place them in the expected place where the submodule will live

This was working super well, I followed this https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#multiple-assets so I created a `conandata.yml` file as expected:

```yml
sources:
  "2.4.1":
    "sources":
        url: "https://github.com/Snaipe/Criterion/archive/refs/tags/v2.4.1.zip"
        sha256: "033c3ac4d9b7cc1bc64ca0cfa352a90b7f33aa8ae077193944457f15eda691be"
    "debugbreak":
        url: "https://github.com/MrAnno/debugbreak/archive/83bf7e933311b88613cbaadeced9c2e2c811054a.zip"
        sha256: "a977b15fb4e45403ab8f9e19b3a63a30ebf35dbe756ec460f7c7e79943e2fbf7"
    "klib":
        url: "https://github.com/attractivechaos/klib/archive/cdb7e9236dc47abf8da7ebd702cc6f7f21f0c502.zip"
        sha256: "93183d074dee843bd6fb571270093c277bf2f7fd6b4ce4c20acf3d5256112acd"

```

In my `conanfile.py` source method I just put something like this:

```py
    def source(self):
        get(self, **self.conan_data['sources'][self.version]['sources'], strip_root=True)

        # We need to get dependencies for building, they are git submodules!
        # get(self, **self.conan_data['sources'][self.version]['debugbreak'], strip_root=True,
        #     destination=path.join(self.source_folder, 'dependencies', 'debugbreak'))
        
        # get(self, **self.conan_data['sources'][self.version]['klib'], strip_root=True,
        #     destination=path.join(self.source_folder, 'dependencies', 'klib'))
```
(Ignore the comments, with those lines it will fail too).

Of course this fails the hook checks, because I am not using `get(self, **self.conan_data['sources'][self.version])` because, well, I can't pass other things. This makes me wonder the support for extra assets is conflicting with the hooks or I am missing something here.

Any ideas?
