### ISSUE TITLE
[question] Can't reproduce RREV while building binary packages locally

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#1877]
I need some conan-center packages for architectures that currently not supported  So I cloned this repo and tried to build something. But the problem is that my locally-cloned recipes and conan-center ones have different RREVs! Looks like that's because `conandata.yml` is filtered somehow during CI on conan-center side, so the recipe revision changes. E.g. for protobuf recipe the repo contains
```YAML
sources:
  3.9.1:
    sha256: 98e615d592d237f94db8bf033fba78cd404d979b0b70351a9e5aaff725398357
    url: https://github.com/protocolbuffers/protobuf/archive/v3.9.1.tar.gz
  3.11.4:
    sha256: a79d19dcdf9139fa4b81206e318e33d245c4c9da1ffed21c87288ed4380426f9
    url: https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz
patches:
  3.9.1:
    - patch_file: "patches/protobuf-3.9.1.patch"
      base_path: "source_subfolder"
  3.11.4:
    - patch_file: "patches/protobuf-3.11.4.patch"
      base_path: "source_subfolder"
```
but if I install the package from `conan-center`, local cache contains the following:
```YAML
patches:
  3.11.4:
  - base_path: source_subfolder
    patch_file: patches/protobuf-3.11.4.patch
sources:
  3.11.4:
    sha256: a79d19dcdf9139fa4b81206e318e33d245c4c9da1ffed21c87288ed4380426f9
    url: https://github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz
```
This is very unfortunate as it effectively prohibits any local/conan-center package mixing. Any idea how to overcome this?
