### ISSUE TITLE
Fail to reproduce pipeline builds locally

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-center-index#19173]
Hello
I have made changes to the net-snmp recipe and added a [pull request](https://github.com/conan-io/conan-center-index/pull/19001)
The [pipeline build](https://c3i.jfrog.io/c3i/misc/summary.html?json=https://c3i.jfrog.io/c3i/misc/logs/pr/19001/21-linux-gcc/net-snmp/5.9.1//summary.json) does however fail

Focussing on this failed build with gcc5 and shared=True: [build](https://c3i.jfrog.io/c3i/misc/logs/pr/19001/21-linux-gcc/net-snmp/5.9.1//9a67b68935020ab4a0749ecbcd48cb22e1cdbf0e-build.txt)

If I try to build locally in the conatiner conanio/gcc5-ubuntu16.04:1.60.0 with command: `conan create recipes/net-snmp/all/ /5.9.1@ --build net-snmp -o:h net-snmp:shared=True` the build succeeds.

I have compared the package summary when the build starts and it is identical between my build and the pipeline build.

My local build:
```
Requirements
    bzip2/1.0.8 from 'tuc-conan-virtual' - Cache
    net-snmp/5.9.1 from local cache - Cache
    openssl/1.1.1q from 'tuc-conan-virtual' - Cache
    pcre/8.45 from 'tuc-conan-virtual' - Cache
    zlib/1.2.13 from 'tuc-conan-virtual' - Cache
Packages
    bzip2/1.0.8:3df6ebb8a308d309e882b21988fd9ea103560e16 - Cache
    net-snmp/5.9.1:9a67b68935020ab4a0749ecbcd48cb22e1cdbf0e - Build
    openssl/1.1.1q:76f87539fc90ff313e0b3182641a9bb558a717d2 - Cache
    pcre/8.45:fab187555fa87e54b51a5e8e8ff95b0f5855d00b - Cache
    zlib/1.2.13:76f87539fc90ff313e0b3182641a9bb558a717d2 - Cache
```
The pipeline build can be seen [here](https://c3i.jfrog.io/c3i/misc/logs/pr/19001/21-linux-gcc/net-snmp/5.9.1//9a67b68935020ab4a0749ecbcd48cb22e1cdbf0e-build.txt)

The build output starts to dirrentiate here while configuring:
![image](https://github.com/conan-io/conan-center-index/assets/48069914/d1bf5d2d-0780-4fb1-b4ae-1bb7dafc6495)

I am, first of all, puzzled regarding why I cannot reproduce the error when building in the container. Is it not the same container being used in the pipeline?

Secondly, I could move on in my investigations if I could see the config.log file produced in the pipeline to see why the differentiating checks fail. Is it possible to see those files?

I have attached the entire local build log: [net-snmp_local.log](https://github.com/conan-io/conan-center-index/files/12329303/net-snmp_local.log)

Regards
Klaus

**Comment by RubenRBS** [comment]
Tagging @uilianries here, our CCI container expert :)

**Comment by uilianries** [comment]
@klausholstjacobsen We do not use the docker image `conanio/gcc5-ubuntu16.04` but the `conanio/gcc5`. 

To understand which version we are running, you need to read the `config_v1.yml` and `config_v2.yml`. Let's take a look together:

These suffixes `v1` and `v2` are related to the Conan client version: Conan 1.x and Conan 2.x, as we run both in CCI. So `config_v1.yml` refers to all CI builds with Conan 1.x only.

There are 2 sections in `config_v1.yml`, the configuration supported, and the docker images used:

https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L70
https://github.com/conan-io/conan-center-index/blob/master/.c3i/config_v1.yml#L188

```
configurations:
  - id: linux-gcc
    epochs: [0]
    hrname: "Linux, GCC"
    content:
      - os: [ "Linux" ]
        arch: [ "x86_64" ]
        compiler:
          - "gcc":
              compiler.libcxx: [ "libstdc++11" ]
              compiler.version: [ "5", "7", "9", "10" ]
              build_type: [ "Release", "Debug" ]
  - id: linux-gcc
    epochs: [20211221, 20220120, 20230606]
    hrname: "Linux, GCC"
    content:
      - os: ["Linux"]
        arch: ["x86_64"]
        compiler:
          - "gcc":
              compiler.libcxx: [ "libstdc++11" ]
              compiler.version: ["5", "7", "9", "10", "11"]
              build_type: ["Release", "Debug"]
....
  Linux:
    x86_64:
      "gcc":
        default: "linux_gcc_${compiler.version}"
        "11": "linux_gcc_${compiler.version}_ubuntu16.04"
      "clang":
        default: "linux_clang_${compiler.version}_ubuntu16.04"
        "11": "linux_clang_${compiler.version}"
```

As you can see, we are running GCC 5, 7, 9, 10 and 11 for Conan 1.x

The label used for them is `linux_gcc_<compiler>`, that's an internal label for Jenkins, but in summary it will translate as the docker image `conanio/gcc<compiler_version>`. Except for GCC 11, that you may note the suffix `ubuntu16.04` which indicates the docker image `conanio/gcc11-ubuntu16.04`. This rule is the same applied for Conan 2.x and Clang docker images.

Now maybe you are thinking "why these people are doing this mess?" We updated our Docker images after years of usage, trying to align to a same base image, keeping glibc, libstdc++ and others important system libraries using same version. However, we have tons of packages built in ConanCenter with older images, so we can't just switch to a newer Docker image without breaking all packages. So our current approach is deprecating those older docker images when introducing a new compiler version.
