### ISSUE TITLE
[question] how to install zookeeper-client-c/3.9.0 in a offline manner

### ISSUE THREAD

**Issue by hartvon** [conan-io/conan-center-index#19332]
### What is your question?

Hi,
I met a problem during installing `zookeeper-client-c`, I cannot download the fille due to slow network connection, as follows:
```
ERROR: zookeeper-client-c/3.9.0: Error in source() method, line 55
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: Error downloading file https://archive.apache.org/dist/zookeeper/zookeeper-3.9.0/apache-zookeeper-3.9.0.tar.gz: 
'HTTPSConnectionPool(host='archive.apache.org', port=443): Read timed out. (read timeout=30)'
```

I can download the archive file manually, I want to kown is there some ways to install the package in a offline manner, or other ways to solve my problem?

Thanks so much.

**Comment by jcar87** [comment]
Hi @hartvon - thank you for asking this question.

If you can download the file manually,  and you can clone the `conan-center-index` repository, you can edit this file:
https://github.com/conan-io/conan-center-index/blob/master/recipes/zookeeper-client-c/all/conandata.yml

and add a mirror (an additional url) pointing to a file in the filesystem with `file:///` (docs [here](https://docs.conan.io/1/reference/conanfile/tools/files/downloads.html?highlight=file#conan-tools-files-download))

It would look something like this:
```
sources:
  "3.9.0":
    url: "https://archive.apache.org/dist/zookeeper/zookeeper-3.9.0/apache-zookeeper-3.9.0.tar.gz"
    url: "file:///home/myuser/downloads/apache-zookeeper-3.9.0.tar.gz"
    sha256: "c7af07e7411c798398bb8cd50f47780d8e014831666c41df6ec6540c143c0da2"
```

you would then have to export or create the recipe from the repository:
```
conan export recipes/zookeeper-client-c/all --version=3.9.0
```

and then you can do conan install normall
