### ISSUE TITLE
[package] yasm/1.3.0: build along

### ISSUE THREAD

**Issue by elderbig** [conan-io/conan-center-index#19945]
### Description

vim ~/.conan2/settings.yml
```yaml
os:
    Windows:
        subsystem: [null, cygwin, msys, msys2, wsl]
    WindowsStore:
        version: ["8.1", "10.0"]
    WindowsCE:
        platform: [ANY]
        version: ["5.0", "6.0", "7.0", "8.0"]
    Linux:
       libc:
            null:
            glibc:
                version: ["2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7",
                          "2.8", "2.9", "2.10", "2.11", "2.12", "2.13", "2.14",
                          "2.15", "2.16", "2.17", "2.18", "2.19", "2.20", "2.21",
                          "2.22", "2.23", "2.24", "2.25", "2.26", "2.27", "2.28",
                          "2.29", "2.30", "2.31", "2.32", "2.33", "2.34", "2.35",
                          "2.36", "2.37", "2.38"]
            musl:
                version: ["0.9", "1.0", "1.1", "1.2"]

```

### Package and Environment Details

* Package Name/Version: **yasm/1.3.0**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.0.10**
* Python version: **Python 3.10.4**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os.libc=glibc
os.libc.version=2.35
build_type=Release

### Steps to reproduce

mkdir test
cd test
vim conanfile.txt
```toml
[requires]
yasm/1.3.0

[generators]
CMakeDeps
CMakeToolchain
```
conan install conanfile.txt --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os.libc=glibc
os.libc.version=2.35

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os.libc=glibc
os.libc.version=2.35


======== Computing dependency graph ========
Graph root
    conanfile.txt: /home/app/temp/test/conanfile.txt
Requirements
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694 - Cache

======== Computing necessary packages ========
Requirements
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694:f07b7878a5d63fd3e889e2a5c740960f305bd377 - Build

======== Installing packages ========
yasm/1.3.0: WARN: Trying to remove corrupted source folder
yasm/1.3.0: WARN: This can take a while for big packages
yasm/1.3.0: Calling source() in /home/sun/.conan2/p/yasmb78308884dd42/s/src
ERROR: yasm/1.3.0: Error in source() method, line 50
	get(self, **self.conan_data["sources"][self.version][0],
	ConanException: sha256 signature failed for 'yasm-1.3.0.tar.gz' file. 
 Provided signature: 3dce6601b495f5b3d45b59f7d2492a340ee7e84b5beca17e48f862502bd5603f  
 Computed signature: 49c1440edfb1b58109b9a3c512b114de83f6bd29e29b3be845b9182920b3ba2f

```

</details>
