### ISSUE TITLE
[request] libcurl/8.4.0

### ISSUE THREAD

**Issue by PengZheng** [conan-io/conan-center-index#20529]
### Package Name/Version

curl/8.4.0

### Changelog

https://curl.se/changes.html#8_4_0

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

This version fixes high severity vulnerability: https://curl.se/docs/CVE-2023-38545.html
Related discussions: https://github.com/curl/curl/discussions/12026

**Comment by jwatson0** [comment]
I'm attempting to build this myself.
Added these sources to `conan-center-index/recipes/libcurl/all/conandata.yml` 
```
  "8.4.0":
    url:
      - "https://curl.se/download/curl-8.4.0.tar.xz"
      - "https://github.com/curl/curl/releases/download/curl-8_4_0/curl-8.4.0.tar.xz"
    sha256: "16c62a9c4af0f703d28bda6d7bbf37ba47055ad3414d70dec63e2e6336f2a82d"
  "8.3.0":
    url:
      - "https://curl.se/download/curl-8.3.0.tar.xz"
      - "https://github.com/curl/curl/releases/download/curl-8_3_0/curl-8.3.0.tar.xz"
    sha256: "376d627767d6c4f05105ab6d497b0d9aba7111770dd9d995225478209c37ea63"
```

Building either `8.3.0` or `8.4.0` on linux results in:
```
ERROR: libcurl/8.4.0: Error in build() method, line 242
	self._patch_sources()
while calling '_patch_sources', line 270
	self._patch_autotools()
while calling '_patch_autotools', line 305
	replace_in_file(self, configure_ac,
	ConanException: replace_in_file didn't find pattern '-lz ' in '/home/jwatson/git/conan-center-index/.conan2/p/b/libcu7363dc94398b3/b/src/configure.ac' file.
```

The recipe looks like it needs an update for patching the sources.
