### ISSUE TITLE
[question] Add a patch where I am adding a new file

### ISSUE THREAD

**Issue by elvisdukaj** [conan-io/conan-center-index#22901]
### What is your question?

Hi! Is it possible to create a patch where a new file is added? My issue is that with Msys2 I need to add a new self-signed certificate from my company. According the [msys2 documentation](https://www.msys2.org/docs/faq/) I need to copy the certificate in `/etc/pki/ca-trust/source/anchors` (inside msys2) and then call `update-ca-trust`.

What I did:

I create a patch file that looks like:

0001_xxx_ca_cert.patch:

```
--- a/msys2-base-x86_64-20231026/msys64/etc/pki/ca-trust/source/anchors/cacert_combined.pem
+++ b/msys2-base-x86_64-20231026/msys64/etc/pki/ca-trust/source/anchors/cacert_combined.pem
@@ -0,0 +1,3231 @@
+-----BEGIN CERTIFICATE-----
+
...
```

Than I modified the `conandata.yml` adding:

```
patches:
  "cci.latest":
    - patch_file: "patches/0001_xxx_ca_cert.patch"
      patch_description: "Adding Company certificate"
```

But I've the `source/target file does not exist`  error message. What is the right way to continue in this case? Any help is appreciated.
