### ISSUE TITLE
[package] poco/1.13.3: sha256sum mismatch

### ISSUE THREAD

**Issue by bigcat26** [conan-io/conan-center-index#23407]
### Description

The SHA256 checksum of the downloaded package does not match the value in conandata.yml.

```yaml
sources:
  "1.13.3":
    url: "https://github.com/pocoproject/poco/archive/poco-1.13.3-release.tar.gz"
    sha256: "0f0012944924052ebbe90d74cd684f5bc5264be805010a177c5b8df1ce313e43"
```

```shell
wget -O - https://github.com/pocoproject/poco/archive/poco-1.13.3-release.tar.gz |sha256sum
9f074d230daf30f550c5bde5528037bdab6aa83b2a06c81a25e89dd3bcb7e419
```

### Package and Environment Details

* Package Name/Version: **poco/1.13.3**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.60.2**
* Python version: **Python 3.11.4**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install poco/1.13.3@ -b poco

### Logs

<details><summary>Click to expand log</summary>

```
Downloading poco-1.13.3-release.tar.gz completed [11066.96k]                             poco/1.13.3: .13.3: 
ERROR: poco/1.13.3: Error in source() method, line 210
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
        ConanException: sha256 signature failed for 'poco-1.13.3-release.tar.gz' file. 
 Provided signature: 0f0012944924052ebbe90d74cd684f5bc5264be805010a177c5b8df1ce313e43  
 Computed signature: 9f074d230daf30f550c5bde5528037bdab6aa83b2a06c81a25e89dd3bcb7e419
```

</details>
