### ISSUE TITLE
[package] approvaltests.cpp/10.13.0: conanfile is not compatible with mirror urls

### ISSUE THREAD

**Issue by markuspi** [conan-io/conan-center-index#26683]
### Description

The recipe file of `approvaltests.cpp` has hardcoded logic that assumes only one source url is present per file. This breaks our downstream automation, where we modify conandata.yml file to add custom mirror urls.

https://github.com/conan-io/conan-center-index/blob/1ac559dd6215d6f2c1f68377c43791c7872c7715/recipes/approvaltests.cpp/all/conanfile.py#L77-L83

Judging by conan's source code of `conan.tools.files.get` and `.download`, I assume a possible fix could be:

```python
         urls = source["url"]
         url = urls[0] if isinstance(urls, (list, tuple)) else urls
         filename = url[url.rfind("/") + 1:] 
```

### Package and Environment Details

* Package Name/Version: **approvaltests.cpp/10.13.0**
* Conan version: **conan 1.66.0**

### Conan profile

n/a

### Steps to reproduce

* download approvaltests.cpp/10.13.0 conanfile.py and conandata.yml 
* edit conandata.yml, adding (valid) mirror urls, i.e.:
```yaml
10.13.0:
  - sha256: c00f6390b81d9924dc646e9d32b61e1e09abda106c13704f714ac349241bb9ff
    url:
    - https://internal/approvaltests.cpp/10.13.0/ApprovalTests.v.10.13.0.hpp
    - https://github.com/approvals/ApprovalTests.cpp/releases/download/v.10.13.0/ApprovalTests.v.10.13.0.hpp
  - sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    url:
    - https://internal/approvaltests.cpp/10.13.0/LICENSE
    - https://raw.githubusercontent.com/approvals/ApprovalTests.cpp/v.10.13.0/LICENSE
```
* try to build the package, observe error 

### Logs

<details><summary>Click to expand log</summary>

Building the package with the updated conandata.yml results in the following error:

```txt
ERROR: approvaltests.cpp/10.13.0: Error in source() method, line 80
	filename = url[url.rfind("/") + 1:]
	AttributeError: 'list' object has no attribute 'rfind'
```

</details>
