### ISSUE TITLE
Impossible to build ImGui TestEngine

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#27763]
@jcar87 @franramirez688 I could be mistaken, but I think there is problem with the way sources are handled after https://github.com/conan-io/conan-center-index/pull/27485. conadata.yml file reduction seems to remove all the `-testengine` keys before uploading to the remote. As a consequence the command `conan install --requires imgui/1.91.8 -o imgui/*:enable_test_engine=True` gets this conandata.yml in cache:
```
sources:
  1.91.8:
    sha256: db3a2e02bfd6c269adf0968950573053d002f40bdfb9ef2e4a90bce804b0f286
    url: https://github.com/ocornut/imgui/archive/v1.91.8.tar.gz
```
And it says `imgui/1.91.8: WARN: No test engine found for this version, removing test engine option`

Shouldn't the test engine sources be added as subkeys to the main version ?

_Originally posted by @ericLemanissier in https://github.com/conan-io/conan-center-index/issues/27485#issuecomment-2992086375_
