### ISSUE TITLE
[package] gtest/1.10.0: missing patch

### ISSUE THREAD

**Issue by oleurodecision** [conan-io/conan-center-index#2841]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gtest/1.10.0**
  * Operating System+version: **Linux Debian 10.4**
  * Compiler+version: **GCC 8**
  * Conan version: **conan 1.29.0**

### Conan profile
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
```

### Steps to reproduce (Include if Applicable)

Just retrieve/build the package with `gtest:debug_postfix="something"`. The value is not used.

### My guess
The `gtest-1.10.0.patch` is not applied but I think it should be.

Seems problem is due to the [conandata.yml file](https://github.com/conan-io/conan-center-index/blob/master/recipes/gtest/all/conandata.yml) :
```yml
patches:
  "1.10.0":
    - patch_file: "patches/gtest-1.10.0.patch"
      base_path: "source_subfolder"
  "1.10.0":
    - patch_file: "patches/gtest-1.10.0-override.patch"
      base_path: "source_subfolder"
```

should be written : 
```yml
patches:
  "1.10.0":
    - patch_file: "patches/gtest-1.10.0.patch"
      base_path: "source_subfolder"
    - patch_file: "patches/gtest-1.10.0-override.patch"
      base_path: "source_subfolder"
```
or am I wrong ?
