### ISSUE TITLE
[question] boost/1.75.0 - is there an easy way to get just one part of Boost without pulling in the whole thing?

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/conan-center-index#4298]
The `boost/1.75/0` package has the following options:

```
options:
    asio_no_deprecated: [True, False]
    bzip2: [True, False]
    debug_level: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    diagnostic_definitions: [True, False]
    error_code_header_only: [True, False]
    extra_b2_flags: ANY
    fPIC: [True, False]
    filesystem_no_deprecated: [True, False]
    header_only: [True, False]
    i18n_backend: ['iconv', 'icu', None]
    layout: ['system', 'versioned', 'tagged', 'b2-default']
    lzma: [True, False]
    magic_autolink: [True, False]
    multithreading: [True, False]
    namespace: ANY
    namespace_alias: [True, False]
    numa: [True, False]
    pch: [True, False]
    python_executable: ANY
    python_version: ANY
    segmented_stacks: [True, False]
    shared: [True, False]
    system_no_deprecated: [True, False]
    without_atomic: [True, False]
    without_chrono: [True, False]
    without_container: [True, False]
    without_context: [True, False]
    without_contract: [True, False]
    without_coroutine: [True, False]
    without_date_time: [True, False]
    without_exception: [True, False]
    without_fiber: [True, False]
    without_filesystem: [True, False]
    without_graph: [True, False]
    without_graph_parallel: [True, False]
    without_iostreams: [True, False]
    without_json: [True, False]
    without_locale: [True, False]
    without_log: [True, False]
    without_math: [True, False]
    without_mpi: [True, False]
    without_nowide: [True, False]
    without_program_options: [True, False]
    without_python: [True, False]
    without_random: [True, False]
    without_regex: [True, False]
    without_serialization: [True, False]
    without_stacktrace: [True, False]
    without_system: [True, False]
    without_test: [True, False]
    without_thread: [True, False]
    without_timer: [True, False]
    without_type_erasure: [True, False]
    without_wave: [True, False]
    zlib: [True, False]
    zstd: [True, False]
```

I know that I can use the `header_only` option to just get the headers and not any of the other libraries... But what if I just want one of the non-header only pieces of boost? (What if I just want "regex" for example?)

Is there an easy way to just enable `regex` without specifying `without_<library>` for all of the other libraries?

Typically projects only use a couple pieces of Boost and installing/compiling it all can be quite time-consuming. I feel like it would be a lot cleaner if there was a way to "opt-in" for the pieces you want instead of "opting-out" of all of the pieces you don't want.
