### ISSUE TITLE
[package] qt/6.x.x: component support

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan-center-index#4736]
The qt 6.x.x package lacks component support. I understand this could be quite a bit of work to add this. I would be willing to put some effort in, but if I am being honest I don't see a good way forward. The generated Qt cmake files contain quite a bit of extra stuff (ref. below). For me the issue with the current setup is that for example:

- not all functionality (tools/functions/macros) is available,
- targets are missing meaning you are not clear on what you are actually using,
- targets are missing which make it hard to link some plugins (like the platform plugins),
- using conan package is non-transparent, and
- order of libraries could be wrong.

To fix the above you need to replicate the functionality contained in Qt, which is mostly targets and properties (see below for example properties). I think there are a few ways to go:

1. make this info available in the package (json, yaml, conf etc.) and generate all files.
1. parse qt cmake files to extract info and generate all files, or
1. use the qt cmake files.

For me options 1 or 3 seem the way to go. Do you see any other options or has there already been some work on this? I expanded a bit on them below. @ericLemanissier what do you think?

<details><summary>Typical qt cmake target properties</summary>
```cmake
 set_target_properties(Qt6::Gui PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_GUI_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/QtGui;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Qt6::Core;d3d11;dxgi;dxguid"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:${_IMPORT_PREFIX}/lib/metatypes/qt6gui_release_metatypes.json>"
  MODULE_PLUGIN_TYPES "accessiblebridge;platforms;platforms_darwin;xcbglintegrations;platformthemes;platforminputcontexts;generic;iconengines;imageformats;egldeviceintegrations"
  QT_DISABLED_PRIVATE_FEATURES "accessibility_atspi_bridge;directfb;directwrite3;evdev;fontconfig;qqnx_imf;integrityfb;kms;drm_atomic;libinput;integrityhid;libinput_axis_api;linuxfb;vsp2;vnc;mtdev;egl_x11;eglfs;eglfs_brcm;eglfs_egldevice;eglfs_gbm;eglfs_vsp2;eglfs_mali;eglfs_viv;eglfs_rcar;eglfs_viv_wl;eglfs_openwfd;eglfs_x11;jpeg;system_jpeg;tslib;xcb;xcb_glx_plugin;xcb_glx;xcb_egl_plugin;xcb_native_painting;xrender;xcb_xlib;xcb_sm;system_xcb_xinput;xkbcommon;xkbcommon_x11;xlib"
  QT_DISABLED_PUBLIC_FEATURES "accessibility_atspi_bridge;fontconfig;opengles2;opengles3;opengles31;opengles32;vulkan;openvg;egl;system_textmarkdownreader"
  QT_ENABLED_PRIVATE_FEATURES "directwrite;direct2d;direct2d1_1;freetype;system_freetype;harfbuzz;system_harfbuzz;vkgen;gif;ico;png;system_png;imageio_text_loading;tuiotouch;multiprocess;raster_64bit"
  QT_ENABLED_PUBLIC_FEATURES "freetype;harfbuzz;dynamicgl;opengl;ico;sessionmanager;texthtmlparser;textmarkdownreader;textmarkdownwriter;textodfwriter;cssparser;draganddrop;action;cursor;clipboard;wheelevent;tabletevent;im;highdpiscaling;validator;standarditemmodel;filesystemmodel;imageformatplugin;movie;imageformat_bmp;imageformat_ppm;imageformat_xbm;imageformat_xpm;imageformat_png;imageformat_jpeg;image_heuristic_mask;image_text;picture;colornames;pdf;desktopservices;systemtrayicon;accessibility;whatsthis;undocommand;undostack;undogroup"
  QT_PLUGINS "QMinimalIntegrationPlugin;QOffscreenIntegrationPlugin;QWindowsIntegrationPlugin;QWindowsDirect2DIntegrationPlugin;QICOPlugin;QGifPlugin;QTuioTouchPlugin;QSvgIconPlugin;QSvgPlugin"
  QT_QMAKE_PRIVATE_CONFIG ""
  QT_QMAKE_PUBLIC_CONFIG ""
  QT_QMAKE_PUBLIC_QT_CONFIG ""
  _qt_config_module_name "gui"
  _qt_module_has_headers "ON"
)
```
</details>

## Option 1

While I think this option will take some work and can be fragile it is quite clear. I attached an example yaml, it does not contain all information that is in a typical qt target as I am not sure what info is needed and what is not. Next to this yaml we would need to generate a few other yaml files defining targets such as Qt6::qmake, typically contained in the tools targets (Qt6::CoreTools). You could use this list to check which libraries (including their dependencies) were built and add the correct targets.

Advantages:

- clear,
- easy to generate proper conan cmake files,

Disadvantages:

- can be fragile,
- new libs require work.

<details><summary>Example components yaml</summary>

```yaml
components:
  "Core":
    Windows:
      systemlibs:
      - "Version"
      - "Winmm"  
      - "Netapi32"
      - "UserEnv"
    Macos:
      systemlibs:
      - "IOKit"
      - "Cocoa"
      - "Security"
    requires:
      - "zlib::zlib"
      - "EntryPoint"
      - "CoreTools"
  "CoreTools":
    build_modules:
      - "Qt6CoreTools.cmake"
  "Concurrent":
    requires:
      - "Core"
  "DBus":
    requires:
      - "DBusTools"
  "EntryPoint"
  "DeviceDiscoverySupport":
    requires:
      "Core"
  "FbSupport":
    requires:
      - "Core"
      - "Gui"
  "Gui":
    requires:
      - "Core"
      - "GuiTools"
  "GuiTools":
    build_modules:
      - "Qt6GuiTools.cmake"
  "Network":
    requires:
      - "Core"
    Windows:
      systemlibs:
      - "DnsApi"
  "OpenGL":
    requires:
      - "Core"
      - "Gui"
  "OpenGLWidgets":
    requires:
      - "OpenGL"
      - "Widgets"
  "PrintSupport":
    requires:
      - "Core"
      - "Gui"
      - "Widgets"
  "Sql":
    requires:
      - "Core"
  "Test":
    requires:
      - "Core"
  "Widgets"
    requires:
      - "WidgetsTools"
      - "Core"
      - "Gui"
  "CoreTools":
    build_modules:
      - "Qt6WidgetsTools.cmake"
  "Xml":
    requires:
      - "Core"
```
</details>

## Option 2

The Qt cmake files are quite structured, so it might be possible to parse them to extract information similar to the yaml and then regenerate them through conan.

Advantages:

- new libraries require no work,
- changes to existing require no work if not major.

Disadvantages:

- fragile parsing of files,
- unclear

## Option 3

This would be to do what the old bincrafter recipes do, just expose the Qt cmake files through conan.

Advantages:

- small effort to implement, and
- very limited maintenance required.

Disadvantages:

- https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged
