### ISSUE TITLE
[question] How to detect we're running on c3i?

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#5429]
We're having a lot of problems with building boost packages on c3i.
See e.g. https://github.com/conan-io/conan-center-index/pull/5420

Often the boost build fails because the test_package is built with a too high parallelism.
The logs contain the line:
```
MSBUILD : error MSB4166: Child node "6" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\J\w\BuildSingleReference@7\10837\d953e04c-152c-463f-8164-f2a7e5bf2b0f\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
  locale.cpp
```

I think it would be useful to detect we're running on c3i/ci and if so, lower the level of parallelism.
e.g.
```python
cmake = CMake(self)
cmake.configure()
if tools.get_env("CI_C3I"):
    cmake.parallel = False
cmake.build()
```

What do you think?

**Comment by jgsogo** [comment]
I would vote to _hide_ this in the `config.yml` file instead of modifying the recipe.

What about...?

**config.yml**
```yaml
versions:
    1.69.0:
      folder: all
    1.70.0:
      folder: all
config:
  env:
     CPU_COUNT: 1  # Will translate to CONAN_CPU_COUNT
```

or

```yaml
versions:
    1.69.0:
      folder: all
      env:
        CPU_COUNT: 1  # Will translate to CONAN_CPU_COUNT
    1.70.0:
      folder: all 
      env:
        CPU_COUNT: 1  # Will translate to CONAN_CPU_COUNT
```

 * It will require to develop this feature in the c3i library (not so complicated)
 * Probably we need to filter variables that are available and values, just in case.

ping @danimtb
